services:
  mongodb:
    image: mongo:latest
    command: mongod --quiet --logpath /dev/null
    # volumes:
    #   - ./data/database/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  echoserver:
    build: 
      context: ./
      dockerfile: "echo-mongo.dockerfile"
    hostname: echoserver
    environment:
      - MONGODB_URI=mongodb://root:rootpassword@mongodb:27017
    depends_on:
      mongodb:
        condition: service_healthy
    ports:
      - 8080:8080